services:
     tag.form.type.tags:
         class: TagBundle\Form\Type\TagType
         arguments: ['@doctrine.orm.entity_manager']
         tags:
            - { name: form.type }
#    tag.example:
#        class: TagBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
