tag:
    resource: "@TagBundle/Resources/config/routing.yml"
    prefix:   /

forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /

offer:
    resource: "@OfferBundle/Resources/config/routing.yml"
    prefix:   /

contact:
    resource: "@ContactBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

home:
    path:     /home
    defaults: { _controller: UserBundle:Default:index }

back:
    path:     /back
    defaults: { _controller: AppBundle:Default:backOffice }

about:
    path:     /about
    defaults: { _controller: AppBundle:Default:about }

showContact:
    path:     /back/contact
    defaults: { _controller: ContactBundle:Contact:show }

createContact:
    path:     /contact
    defaults: { _controller: ContactBundle:Contact:create }

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"